In [4]:
data = open('data2.txt', 'r').read()
for i in data.split(', '):
    print(i)

['The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.'
'It is our choices
Harry
that show what we truly are
far more than our abilities.'
'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.'
'The person
be it gentleman or lady
who has not pleasure in a good novel
must be intolerably stupid.'
"Imperfection is beauty
madness is genius and it's better to be absolutely ridiculous than absolutely boring."
'Try not to become a man of success. Rather become a man of value.'
'It is better to be hated for what you are than to be loved for what you are not.'
"I have not failed. I've just found 10,000 ways that won't work."
"A woman is like a tea bag; you never know how strong it is until it's in hot water."
'A day without sunshine is like
you know
night.'
"This life is what you make it. No matter what
you're going to mess up sometimes
it's a universal truth

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [6]:
for i in data.split(', '):
    tokenizer.fit_on_texts([i])

In [7]:
tokenizer.word_index

{'you': 1,
 "'": 2,
 'to': 3,
 'is': 4,
 'a': 5,
 'the': 6,
 'of': 7,
 'and': 8,
 'i': 9,
 'it': 10,
 'not': 11,
 'be': 12,
 'that': 13,
 'in': 14,
 'but': 15,
 'love': 16,
 'can': 17,
 'your': 18,
 'who': 19,
 'will': 20,
 'have': 21,
 'what': 22,
 'are': 23,
 'all': 24,
 'if': 25,
 'as': 26,
 'one': 27,
 'up': 28,
 'for': 29,
 'with': 30,
 'my': 31,
 'or': 32,
 'never': 33,
 'no': 34,
 'more': 35,
 'her': 36,
 'she': 37,
 'think': 38,
 "it's": 39,
 'make': 40,
 'so': 41,
 'when': 42,
 "'the": 43,
 'we': 44,
 'than': 45,
 'only': 46,
 'life': 47,
 'like': 48,
 'because': 49,
 "'i": 50,
 'from': 51,
 'do': 52,
 "'it": 53,
 "don't": 54,
 'them': 55,
 'me': 56,
 'live': 57,
 'good': 58,
 'just': 59,
 'know': 60,
 'day': 61,
 'going': 62,
 'give': 63,
 'at': 64,
 'keep': 65,
 'may': 66,
 'people': 67,
 'time': 68,
 'book': 69,
 'see': 70,
 'world': 71,
 'our': 72,
 'without': 73,
 'has': 74,
 'how': 75,
 'truth': 76,
 'friends': 77,
 'go': 78,
 'on': 79,
 "'if": 80,
 'read': 81,
 'an': 82

In [8]:
VOCAB_SIZE = len(tokenizer.word_index)

In [9]:
VOCAB_SIZE

712

In [13]:
input_seq = []
for sent in data.split('\n'):
    tokenized_sent = tokenizer.texts_to_sequences([sent])[0]
    for i in range(1, len(tokenized_sent)):
        ngram = tokenized_sent[:i+1]
        input_seq.append(ngram)
input_seq

[[43, 71],
 [43, 71, 26],
 [43, 71, 26, 44],
 [43, 71, 26, 44, 21],
 [43, 71, 26, 44, 21, 285],
 [43, 71, 26, 44, 21, 285, 10],
 [43, 71, 26, 44, 21, 285, 10, 4],
 [43, 71, 26, 44, 21, 285, 10, 4, 5],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7, 72],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7, 72, 109],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7, 72, 109, 10],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7, 72, 109, 10, 287],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7, 72, 109, 10, 287, 12],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7, 72, 109, 10, 287, 12, 288],
 [43, 71, 26, 44, 21, 285, 10, 4, 5, 286, 7, 72, 109, 10, 287, 12, 288, 73],
 [43,
  71,
  26,
  44,
  21,
  285,
  10,
  4,
  5,
  286,
  7,
  72,
  109,
  10,
  287,
  12,
  288,
  73,
  289],
 [43,
  71,
  26,
  44,
  21,
  285,
  10,
  4,
  5,
  286,
  7,
  72,
  109,
  10,
  287,
  12,
  288,
  73,
  289,
  72],
 [43,
  71,
  26,
  44

In [14]:
MAX_INPUT_LEN = max(len(x) for x in input_seq)
MAX_INPUT_LEN

53

In [15]:
from tensorflow.keras.utils import pad_sequences
padded_input = pad_sequences(input_seq, maxlen=MAX_INPUT_LEN, padding='pre')
padded_input

array([[  0,   0,   0, ...,   0,  43,  71],
       [  0,   0,   0, ...,  43,  71,  26],
       [  0,   0,   0, ...,  71,  26,  44],
       ...,
       [  0,   0,   0, ...,   3,  65, 170],
       [  0,   0,   0, ...,  65, 170, 712],
       [  0,   0,   0, ..., 170, 712,   2]])

In [16]:
X = padded_input[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0,  43],
       [  0,   0,   0, ...,   0,  43,  71],
       [  0,   0,   0, ...,  43,  71,  26],
       ...,
       [  0,   0,   0, ...,   4,   3,  65],
       [  0,   0,   0, ...,   3,  65, 170],
       [  0,   0,   0, ...,  65, 170, 712]])

In [17]:
y = padded_input[:,-1]
y

array([ 71,  26,  44, ..., 170, 712,   2])

In [18]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=VOCAB_SIZE+1)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [19]:
print(X.shape)
print(y.shape)

(2209, 52)
(2209, 713)


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Embedding, Dense
model = Sequential()
model.add(Embedding(713, 120, input_length=52))
model.add(LSTM(160))
model.add(Dropout(0.2))
model.add(Dense(713, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X,y, epochs=110)

Epoch 1/110
70/70 [==============================] - 6s 49ms/step - loss: 6.0517 - accuracy: 0.0285
Epoch 2/110
70/70 [==============================] - 3s 47ms/step - loss: 5.6784 - accuracy: 0.0349
Epoch 3/110
70/70 [==============================] - 3s 47ms/step - loss: 5.5963 - accuracy: 0.0376
Epoch 4/110
70/70 [==============================] - 3s 49ms/step - loss: 5.5000 - accuracy: 0.0367
Epoch 5/110
70/70 [==============================] - 4s 50ms/step - loss: 5.4218 - accuracy: 0.0421
Epoch 6/110
70/70 [==============================] - 4s 55ms/step - loss: 5.3348 - accuracy: 0.0561
Epoch 7/110
70/70 [==============================] - 5s 68ms/step - loss: 5.2278 - accuracy: 0.0702
Epoch 8/110
70/70 [==============================] - 4s 62ms/step - loss: 5.0811 - accuracy: 0.0937
Epoch 9/110
70/70 [==============================] - 4s 51ms/step - loss: 4.9260 - accuracy: 0.1105
Epoch 10/110
70/70 [==============================] - 3s 50ms/step - loss: 4.7743 - accuracy: 0.1272

70/70 [==============================] - 3s 43ms/step - loss: 0.2471 - accuracy: 0.9375
Epoch 83/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2345 - accuracy: 0.9366
Epoch 84/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2416 - accuracy: 0.9339
Epoch 85/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2365 - accuracy: 0.9339
Epoch 86/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2279 - accuracy: 0.9393
Epoch 87/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2315 - accuracy: 0.9362
Epoch 88/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2275 - accuracy: 0.9348
Epoch 89/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2338 - accuracy: 0.9348
Epoch 90/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2187 - accuracy: 0.9393
Epoch 91/110
70/70 [==============================] - 3s 43ms/step - loss: 0.2086 - accuracy: 0.9371
Epo

In [53]:
import numpy as np
text = 'she'
max_length = 100
for i in range(25):
    token = tokenizer.texts_to_sequences([text])[0]
    pad = pad_sequences([token], maxlen=53,padding='pre')
    pred = np.argmax(model.predict(pad))
    for word,index in tokenizer.word_index.items():
        if index == pred:
            text = text + ' '+ word
print(text)


1/1 [==============================] - 0s 22ms/step
she will give you a part of her that she knows you can break—her heart so don't hurt her you don't strong it is until it's


In [54]:
model.save('model.h5')

C:\Users\HINDOL\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
